#!/usr/bin/env julia

# Benchmark Utilities
# Helper functions for benchmark result collection and reporting

using BenchmarkTools
using JSON3
using Dates
using Printf

"""
    BenchmarkResult

Stores results of a single benchmark run.
"""
struct BenchmarkResult
    name::String
    median_ns::Float64
    mean_ns::Float64
    min_ns::Float64
    max_ns::Float64
    allocs::Int
    memory_bytes::Int
end

function BenchmarkResult(name::String, trial::BenchmarkTools.Trial)::BenchmarkResult
    return BenchmarkResult(name,
                           median(trial).time,
                           mean(trial).time,
                           minimum(trial).time,
                           maximum(trial).time,
                           trial.allocs,
                           trial.memory)
end

"""
    BenchmarkSuite

Collects multiple benchmark results.
"""
mutable struct BenchmarkSuite
    name::String
    results::Vector{BenchmarkResult}
    timestamp::DateTime
end

BenchmarkSuite(name::String) = BenchmarkSuite(name, BenchmarkResult[], now())

function Base.push!(suite::BenchmarkSuite, name::String,
                    trial::BenchmarkTools.Trial)::Nothing
    push!(suite.results, BenchmarkResult(name, trial))
    return nothing
end

"""
    format_time(ns::Float64) -> String

Format nanoseconds to human-readable string.
"""
function format_time(ns::Float64)::String
    if ns < 1_000
        return @sprintf("%.2f ns", ns)
    elseif ns < 1_000_000
        return @sprintf("%.2f μs", ns / 1_000)
    elseif ns < 1_000_000_000
        return @sprintf("%.2f ms", ns / 1_000_000)
    else
        return @sprintf("%.2f s", ns / 1_000_000_000)
    end
end

"""
    format_memory(bytes::Int) -> String

Format bytes to human-readable string.
"""
function format_memory(bytes::Int)::String
    if bytes < 1_024
        return "$bytes B"
    elseif bytes < 1_024^2
        return @sprintf("%.2f KiB", bytes / 1_024)
    elseif bytes < 1_024^3
        return @sprintf("%.2f MiB", bytes / 1_024^2)
    else
        return @sprintf("%.2f GiB", bytes / 1_024^3)
    end
end

"""
    save_json(suite::BenchmarkSuite, path::String) -> Nothing

Save benchmark results to JSON file.
"""
function save_json(suite::BenchmarkSuite, path::String)::Nothing
    data = Dict("name" => suite.name,
                "timestamp" => Dates.format(suite.timestamp, "yyyy-mm-dd HH:MM:SS"),
                "results" => [Dict("name" => r.name,
                                   "median_ns" => r.median_ns,
                                   "mean_ns" => r.mean_ns,
                                   "min_ns" => r.min_ns,
                                   "max_ns" => r.max_ns,
                                   "allocs" => r.allocs,
                                   "memory_bytes" => r.memory_bytes) for r in suite.results])

    mkpath(dirname(path))
    open(path, "w") do io
        JSON3.pretty(io, data)
    end

    return nothing
end

"""
    save_markdown(suite::BenchmarkSuite, path::String) -> Nothing

Save benchmark results to Markdown report.
"""
function save_markdown(suite::BenchmarkSuite, path::String)::Nothing
    mkpath(dirname(path))

    open(path, "w") do io
        println(io, "# $(suite.name)")
        println(io)
        println(io,
                "**Generated:** $(Dates.format(suite.timestamp, "yyyy-mm-dd HH:MM:SS"))")
        println(io)
        println(io, "## Results")
        println(io)
        println(io, "| Benchmark | Median | Mean | Min | Max | Allocs | Memory |")
        println(io, "|-----------|--------|------|-----|-----|--------|--------|")

        for r in suite.results
            println(io,
                    "| $(r.name) | $(format_time(r.median_ns)) | $(format_time(r.mean_ns)) | $(format_time(r.min_ns)) | $(format_time(r.max_ns)) | $(r.allocs) | $(format_memory(r.memory_bytes)) |")
        end

        println(io)
        println(io, "---")
        println(io)
        println(io, "Generated by SQLSketch.jl Benchmark Suite")
    end

    return nothing
end

"""
    save_results(suite::BenchmarkSuite) -> Nothing

Save benchmark results to multiple formats:

  - `bench/results/latest.json` - Latest results (overwritten)
  - `bench/results/latest.md` - Human-readable report (overwritten)
  - `bench/results/YYYYMMDD_HHMMSS.json` - Timestamped history
"""
function save_results(suite::BenchmarkSuite)::Nothing
    results_dir = joinpath(@__DIR__, "results")

    # Save latest results (overwrite)
    save_json(suite, joinpath(results_dir, "latest.json"))
    save_markdown(suite, joinpath(results_dir, "latest.md"))

    # Save timestamped history
    timestamp_str = Dates.format(suite.timestamp, "yyyymmdd_HHMMSS")
    save_json(suite, joinpath(results_dir, "$(timestamp_str).json"))

    println()
    println("=" ^ 80)
    println("Results saved:")
    println("  - bench/results/latest.json")
    println("  - bench/results/latest.md")
    println("  - bench/results/$(timestamp_str).json")
    println("=" ^ 80)

    return nothing
end
